steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/quickstart-image"
      - "--file=./prod.Dockerfile"
      - .
images:
  - "gcr.io/$PROJECT_ID/quickstart-image"
